CONTAINER quaddisc
{
	NAME quaddisc;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		REAL PY_QUADDISC_RADIUS			{ UNIT METER; MIN 0.0; }
		LONG PY_QUADDISC_RINGS			{ MIN 1; }
		LONG PY_QUADDISC_SUBDIVISIONS	{ MIN 0; }
	}

	INCLUDE Oprimitiveaxis;

    GROUP PY_QUADDISC_SMOOTHING
    {
        LONG PY_QUADDISC_SMOOTHING_ITERATIONS { MIN 0; MAX 100; }
        REAL PY_QUADDISC_SMOOTHING_STIFFNESS { MIN 0.0; MAX 1.0; STEP 0.1; }
    }
}